// Package ethtypes builds and encodes Ethereum transactions.
//
// It replaces go-ethereum's core/types, the last and by far the most
// delicate part of removing that LGPL dependency. See docs/LICENSING.md
// for why the dependency is going, and
// docs/engineering/GO-ETHEREUM-REMOVAL.md for the plan this is step five
// of.
//
// The reason this file is worth reading carefully: an encoding mistake
// here does not produce an error. It produces a signature that recovers to
// the correct address over a transaction that is not the one anybody
// authorised -- a different recipient, a different amount, or a
// transaction valid on a chain it was not meant for. Nothing downstream
// can detect that, because every downstream check is performed against
// these same bytes.
//
// So nothing here is trusted to a second reading of the specification.
// Every encoding path is pinned to vectors generated by go-ethereum
// itself, byte for byte, including the signing hash and the final
// transaction hash (testdata_txvectors.json).
package ethtypes

import (
	"math/big"
)

// RLP is the encoding Ethereum uses for everything on the wire.
//
// Two shapes -- a byte string and a list -- with the length folded into a
// prefix byte. The rules are short and every one of them has an edge case
// that produces valid-looking wrong output when got wrong, which is why
// each is spelled out rather than compressed.

// rlpString encodes a byte string.
func rlpString(b []byte) []byte {
	// A single byte below 0x80 is its own encoding, with no prefix. This
	// is the case that makes "just always write a length prefix" wrong.
	if len(b) == 1 && b[0] < 0x80 {
		return []byte{b[0]}
	}
	return append(rlpLengthPrefix(len(b), 0x80), b...)
}

// rlpList encodes an already-concatenated list payload.
func rlpList(payload []byte) []byte {
	return append(rlpLengthPrefix(len(payload), 0xc0), payload...)
}

// rlpLengthPrefix builds the prefix for a string (offset 0x80) or a list
// (offset 0xc0).
func rlpLengthPrefix(length int, offset byte) []byte {
	if length <= 55 {
		return []byte{offset + byte(length)}
	}
	// Longer than 55 bytes: the prefix carries the length OF the length,
	// then the length itself, big-endian and minimal.
	lenBytes := bigEndian(uint64(length))
	return append([]byte{offset + 55 + byte(len(lenBytes))}, lenBytes...)
}

// bigEndian renders a uint64 with no leading zero bytes.
func bigEndian(v uint64) []byte {
	if v == 0 {
		return nil
	}
	var buf [8]byte
	i := 8
	for v > 0 {
		i--
		buf[i] = byte(v)
		v >>= 8
	}
	return buf[i:]
}

// rlpUint encodes an integer.
//
// Zero encodes as the empty string (0x80), NOT as a zero byte. That is the
// single most common RLP mistake: 0x00 is a valid one-byte string and
// encodes as itself, so a zero nonce written that way produces a
// well-formed transaction with a different hash from the one every other
// client computes.
func rlpUint(v uint64) []byte {
	return rlpString(bigEndian(v))
}

// rlpBig encodes an arbitrary-precision integer.
//
// Same rule: zero is the empty string. big.Int.Bytes() already strips
// leading zeroes and returns nil for zero, which is exactly what is
// wanted -- a leading zero byte would be a non-canonical encoding that
// some clients reject outright.
func rlpBig(v *big.Int) []byte {
	if v == nil {
		return rlpString(nil)
	}
	if v.Sign() < 0 {
		// Unrepresentable rather than silently encoded as its magnitude.
		// There is no negative quantity in an Ethereum transaction, so
		// reaching here means a caller computed something wrong.
		panic("ethtypes: refusing to RLP-encode a negative integer")
	}
	return rlpString(v.Bytes())
}

// concat joins encoded items into a list payload.
func concat(items ...[]byte) []byte {
	var out []byte
	for _, item := range items {
		out = append(out, item...)
	}
	return out
}
