{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ofb.fullname" . }}
  labels:
    {{- include "ofb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: openfireblocks
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      {{- if .Values.metrics.tokenSecret }}
      bearerTokenSecret:
        name: {{ .Values.metrics.tokenSecret | quote }}
        key: metrics-token
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
