-- services/marketplace: third-party integrations (webhook/api_key/oauth) and
-- their delivery logs. Distinct from services/webhooks' webhooks table --
-- this is the customer-facing "connect an app" surface, that one is the
-- lower-level event-publishing mechanism used elsewhere in the platform.
CREATE TABLE integrations (
  integration_id  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_id     UUID NOT NULL REFERENCES customers(customer_id),
  name            VARCHAR(255) NOT NULL,
  description     TEXT,
  type            VARCHAR(50) NOT NULL CHECK (type IN ('webhook', 'api_key', 'oauth', 'custom')),
  status          VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  config          JSONB NOT NULL DEFAULT '{}'::JSONB,
  webhook_url     VARCHAR(2048),
  webhook_secret  VARCHAR(255),
  -- Stored as generated by CreateIntegration today: plaintext, not hashed.
  -- services/auth's api_keys table hashes + stores only a lookup prefix
  -- (see api-key.util.ts); this table doesn't follow that pattern yet. Not
  -- fixed in this pass -- flagged as a known gap, not silently relabeled.
  api_key         VARCHAR(255),
  events          TEXT[] NOT NULL DEFAULT '{}',
  retry_policy    JSONB,
  rate_limit      JSONB,
  created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
  last_activated  TIMESTAMP
);

CREATE INDEX idx_integrations_customer ON integrations(customer_id);
CREATE INDEX idx_integrations_status ON integrations(status);

CREATE TABLE integration_webhook_logs (
  log_id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  integration_id  UUID NOT NULL REFERENCES integrations(integration_id),
  event_id        UUID NOT NULL,
  event_type      VARCHAR(100) NOT NULL,
  status_code     INT,
  response_time_ms INT,
  success         BOOLEAN NOT NULL DEFAULT FALSE,
  error_message   TEXT,
  attempt         INT NOT NULL DEFAULT 1,
  next_retry_at   TIMESTAMP,
  created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_integration_webhook_logs_integration ON integration_webhook_logs(integration_id);
