package ethcrypto

import (
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"math/big"
	"strings"
	"testing"
)

// Pinning the replacement to what go-ethereum produced.
//
// These vectors were generated by go-ethereum itself, before it was
// removed, and committed rather than recomputed. That is the point: a test
// that checks this package against a second reading of the specification
// proves only that the same person made the same mistake twice. A test
// against the output of the library being replaced proves the replacement
// is a replacement.
//
// The first vector is independently checkable. Private key 1 yields
// 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf, which is one of the most
// widely published addresses in Ethereum, so a reader can confirm the
// generator was not itself wrong without running anything.

//go:embed testdata_vectors.json
var vectorsJSON []byte

type vector struct {
	Priv         string `json:"priv"`
	Uncompressed string `json:"uncompressed"`
	Compressed   string `json:"compressed"`
	Address      string `json:"address"`
}

func vectors(t *testing.T) []vector {
	t.Helper()
	var vs []vector
	if err := json.Unmarshal(vectorsJSON, &vs); err != nil {
		t.Fatalf("reading vectors: %v", err)
	}
	if len(vs) < 40 {
		t.Fatalf("only %d vectors; the golden file looks truncated", len(vs))
	}
	return vs
}

// pubFor derives the public point for a vector's private scalar, using the
// curve this package exposes.
func pubFor(t *testing.T, v vector) (*big.Int, *big.Int) {
	t.Helper()
	d, ok := new(big.Int).SetString(v.Priv, 16)
	if !ok {
		t.Fatalf("bad private scalar in vector: %q", v.Priv)
	}
	return S256().ScalarBaseMult(d.Bytes())
}

func TestUncompressedEncodingMatchesGoEthereum(t *testing.T) {
	for _, v := range vectors(t) {
		x, y := pubFor(t, v)
		got := hex.EncodeToString(MarshalPubkey(x, y))
		if got != v.Uncompressed {
			t.Errorf("priv %s:\n got %s\nwant %s", v.Priv, got, v.Uncompressed)
		}
	}
}

func TestCompressedEncodingMatchesGoEthereum(t *testing.T) {
	for _, v := range vectors(t) {
		x, y := pubFor(t, v)
		got := hex.EncodeToString(CompressPubkey(x, y))
		if got != v.Compressed {
			t.Errorf("priv %s:\n got %s\nwant %s", v.Priv, got, v.Compressed)
		}
	}
}

// The one that matters. An address derived with the wrong hash, or from
// the wrong bytes, is a well-formed address for an account nobody
// controls -- and money sent to it is gone.
func TestAddressMatchesGoEthereum(t *testing.T) {
	for _, v := range vectors(t) {
		x, y := pubFor(t, v)
		if got := Address(x, y); got != v.Address {
			t.Errorf("priv %s:\n got %s\nwant %s", v.Priv, got, v.Address)
		}
	}
}

// Independently verifiable without trusting the generator.
func TestTheWellKnownAddressForPrivateKeyOne(t *testing.T) {
	x, y := S256().ScalarBaseMult(big.NewInt(1).Bytes())

	if got := Address(x, y); got != "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf" {
		t.Errorf("private key 1 derived %s", got)
	}
}

// Keccak-256, not SHA3-256. The two differ only in padding and produce
// entirely different digests, so this is the mistake that would make every
// address in the platform wrong in a way nothing else would notice.
func TestKeccakIsTheLegacyVariantNotSha3(t *testing.T) {
	// The empty-input Keccak-256 digest, a published constant.
	const emptyKeccak = "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
	// SHA3-256 of the empty string, for contrast.
	const emptySha3 = "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a"

	got := hex.EncodeToString(Keccak256(nil))
	if got == emptySha3 {
		t.Fatal("this is SHA3-256, not Keccak-256; every address derived here would be wrong")
	}
	if got != emptyKeccak {
		t.Errorf("Keccak256(empty) = %s", got)
	}
}

// A coordinate with leading zero bytes must still encode to 32 bytes.
// big.Int drops them, and one byte short shifts everything after it,
// producing a different key that is still structurally valid.
func TestCoordinatesArePaddedToThirtyTwoBytes(t *testing.T) {
	// Search the vectors for a key with a short X or Y.
	found := false
	for _, v := range vectors(t) {
		x, y := pubFor(t, v)
		if len(x.Bytes()) < 32 || len(y.Bytes()) < 32 {
			found = true
			enc := MarshalPubkey(x, y)
			if len(enc) != 65 {
				t.Fatalf("encoding is %d bytes, not 65", len(enc))
			}
			if hex.EncodeToString(enc) != v.Uncompressed {
				t.Errorf("a short coordinate encoded as %s, want %s",
					hex.EncodeToString(enc), v.Uncompressed)
			}
		}
	}
	if !found {
		t.Skip("no vector in the set happens to have a short coordinate")
	}
	// Regardless of the search, the invariant holds for every vector.
	for _, v := range vectors(t) {
		x, y := pubFor(t, v)
		if len(MarshalPubkey(x, y)) != 65 || len(CompressPubkey(x, y)) != 33 {
			t.Errorf("priv %s encoded to the wrong length", v.Priv)
		}
	}
}

// -- EIP-55 --

// The checksum is what catches a mistyped address before it becomes a
// payment to a stranger, so it has to be exactly right rather than
// approximately.
func TestChecksumMatchesTheEIP55Examples(t *testing.T) {
	// The examples from EIP-55 itself.
	for _, want := range []string{
		"0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed",
		"0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359",
		"0xdbF03B407c01E7cD3CBea99509d93f8DDDC8C6FB",
		"0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9aDb",
	} {
		raw, err := ParseAddress(want)
		if err != nil {
			t.Fatalf("parsing %s: %v", want, err)
		}
		if got := ChecksumAddress(raw); got != want {
			t.Errorf("checksum:\n got %s\nwant %s", got, want)
		}
	}
}

// Checksumming is idempotent and case-insensitive on input.
func TestChecksumIsStableWhateverTheInputCase(t *testing.T) {
	const want = "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed"

	for _, in := range []string{want, strings.ToLower(want), strings.ToUpper("5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed")} {
		raw, err := ParseAddress(in)
		if err != nil {
			t.Fatalf("parsing %q: %v", in, err)
		}
		if got := ChecksumAddress(raw); got != want {
			t.Errorf("from %q got %s", in, got)
		}
	}
}

// Every vector's address carries a valid checksum, which is a second,
// independent check on the whole derivation: a wrong address would have to
// be wrong in a way that still checksummed to itself.
func TestEveryDerivedAddressSelfChecksums(t *testing.T) {
	for _, v := range vectors(t) {
		raw, err := ParseAddress(v.Address)
		if err != nil {
			t.Fatalf("vector address %q does not parse: %v", v.Address, err)
		}
		if got := ChecksumAddress(raw); got != v.Address {
			t.Errorf("%s does not checksum to itself (got %s)", v.Address, got)
		}
	}
}

func TestParseAddressRejectsWhatIsNotAnAddress(t *testing.T) {
	for _, s := range []string{
		"",
		"0x",
		"0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAe",   // 39 nibbles
		"0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAedd", // 41
		"0xZZAeb6053F3E94C9b9A09f33669435E7Ef1BeAed",  // not hex
	} {
		if _, err := ParseAddress(s); err == nil {
			t.Errorf("%q was accepted as an address", s)
		}
		if IsHexAddress(s) {
			t.Errorf("IsHexAddress(%q) is true", s)
		}
	}
}

func TestParseAddressAcceptsBothPrefixedAndBare(t *testing.T) {
	const bare = "5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed"

	a, err := ParseAddress(bare)
	if err != nil {
		t.Fatalf("bare: %v", err)
	}
	b, err := ParseAddress("0x" + bare)
	if err != nil {
		t.Fatalf("prefixed: %v", err)
	}
	if hex.EncodeToString(a) != hex.EncodeToString(b) {
		t.Error("the same address parsed differently with and without the 0x prefix")
	}
}
