package main

import (
	"crypto/ed25519"
	"encoding/hex"
	"math/big"
	"strings"
	"testing"
	"time"

	"github.com/btcsuite/btcd/btcec/v2"
	btcecdsa "github.com/btcsuite/btcd/btcec/v2/ecdsa"
	"github.com/btcsuite/btcutil/base58"
)

// Independent known answers for the Cosmos address derivation: generated by a
// separate bech32 + RIPEMD160 implementation that was itself checked against
// the BIP-173 published vector. Private key 1, i.e. the secp256k1 generator.
const generatorCompressed = "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"

func TestCosmosAddressKnownAnswers(t *testing.T) {
	pub, _ := hex.DecodeString(generatorCompressed)
	for prefix, want := range map[string]string{
		"cosmos": "cosmos1w508d6qejxtdg4y5r3zarvary0c5xw7k6ah60c",
		"osmo":   "osmo1w508d6qejxtdg4y5r3zarvary0c5xw7kjxy2e2",
	} {
		got, err := CosmosAddress(pub, prefix)
		if err != nil || got != want {
			t.Errorf("prefix %s: got %q (%v), want %q", prefix, got, err, want)
		}
	}
	if _, err := CosmosAddress(pub[:32], "cosmos"); err == nil {
		t.Error("an uncompressed or truncated key was accepted")
	}
	if _, err := CosmosAddress(pub, ""); err == nil {
		t.Error("an empty prefix was accepted")
	}
}

func TestEveryCosmosFamilyChainResolvesToSecp256k1(t *testing.T) {
	for _, c := range []string{"cosmos", "cosmos-hub", "osmosis"} {
		if cv, err := CurveForChain(c); err != nil || cv != CurveSecp256k1 {
			t.Errorf("%s: %v %v", c, cv, err)
		}
	}
}

func TestKeygenForAnUnknownChainIsRefusedBeforeAnythingStarts(t *testing.T) {
	m := NewTSSPartyManager(1, nil)
	if err := m.StartKeygenForChain("x", 1, map[int]string{1: "http://x"}, "dogecoin"); err == nil {
		t.Fatal("an unknown chain started a ceremony")
	}
}

// A Solana key made through the chain name must land on Ed25519 and carry the
// base58 public key as its address. This is the path the orchestrator uses;
// before StartKeygenForChain existed it sent a field nobody read and every
// Solana key was generated on secp256k1.
func TestSolanaKeygenByChainNameProducesAnEd25519Address(t *testing.T) {
	t.Setenv("TSS_ALLOW_UNAUTHENTICATED_PEERS", "1")
	key := runKeygenOverHTTPFor(t, CurveEd25519, "solana")
	pub, err := hex.DecodeString(key.publicKey)
	if err != nil || len(pub) != ed25519.PublicKeySize {
		t.Fatalf("public key: %v len=%d", err, len(pub))
	}
	if key.address != base58.Encode(pub) {
		t.Fatalf("address %q is not the base58 public key %q", key.address, base58.Encode(pub))
	}
}

// A Cosmos key must be a secp256k1 key whose address is bech32, and a
// threshold signature over a digest must verify as an ordinary secp256k1
// signature against the compressed group key -- which is what a Cosmos node
// does with it.
func TestCosmosKeygenAndSignatureByChainName(t *testing.T) {
	t.Setenv("TSS_ALLOW_UNAUTHENTICATED_PEERS", "1")
	if testing.Short() {
		t.Skip("secp256k1 DKG generates Paillier pre-parameters; skipped in -short")
	}
	key := runKeygenOverHTTPFor(t, CurveSecp256k1, "cosmos")

	if !strings.HasPrefix(key.address, "cosmos1") || strings.HasPrefix(key.address, "0x") {
		t.Fatalf("address %q is not a bech32 cosmos address", key.address)
	}
	uncompressed, err := hex.DecodeString(key.publicKey)
	if err != nil {
		t.Fatal(err)
	}
	pk, err := btcec.ParsePubKey(append([]byte{0x04}, trim04(uncompressed)...))
	if err != nil {
		t.Fatalf("group public key does not parse as secp256k1: %v", err)
	}
	if want, _ := CosmosAddress(pk.SerializeCompressed(), "cosmos"); want != key.address {
		t.Fatalf("address %q is not derived from the group key (want %q)", key.address, want)
	}

	digest := make([]byte, 32)
	copy(digest, []byte("cosmos sign doc hash for the test"))
	committee := []int{1, 3}
	signID := "cosmos-signing-test"
	for _, id := range committee {
		if err := key.managers[id].StartSigning(signID, key.ceremonyID, digest, committee); err != nil {
			t.Fatalf("party %d: StartSigning: %v", id, err)
		}
	}
	var sigHex string
	for deadline := time.Now().Add(3 * time.Minute); time.Now().Before(deadline); time.Sleep(200 * time.Millisecond) {
		st, err := key.managers[committee[0]].GetSigningStatus(signID)
		if err != nil {
			t.Fatal(err)
		}
		if st.Status == ceremonyFailed {
			t.Fatalf("signing failed: %s", st.Error)
		}
		if st.Status == ceremonyCompleted && st.Signature != "" {
			sigHex = st.Signature
			break
		}
	}
	if sigHex == "" {
		t.Fatal("no signature produced")
	}
	raw, _ := hex.DecodeString(sigHex)
	if len(raw) < 64 {
		t.Fatalf("signature is %d bytes", len(raw))
	}
	var r, s btcec.ModNScalar
	r.SetByteSlice(raw[:32])
	s.SetByteSlice(raw[32:64])
	if !btcecdsa.NewSignature(&r, &s).Verify(digest, pk) {
		t.Fatal("the threshold signature does not verify as secp256k1 against the group key")
	}
	_ = big.NewInt
}

func trim04(b []byte) []byte {
	if len(b) == 65 && b[0] == 0x04 {
		return b[1:]
	}
	return b
}
